### ISSUE TITLE
Quantum is renamed to Neutron

### ISSUE THREAD

**Issue by oussemos** [openvswitch/openvswitch.github.io#29]
The Quantum Openstack Plugin is now renamed Neutron, so the documentation page should be updated

Openstack official announce: https://wiki.openstack.org/wiki/Network/neutron-renaming

**Comment by russellb** [comment]
Are you referring to http://openvswitch.org/openstack/documentation/ ?  I think all of that should just be removed as outdated and unmaintained docs.

I can't find that content actually linked anywhere on openvswitch.org.  How did you find it?

**Comment by russellb** [comment]
I removed the OpenStack docs.  Please let us know if there are old references somewhere that need to be cleaned up.
